spring.datasource.url=jdbc:postgresql://postgres-db:5432/order_db
spring.datasource.username=admin
spring.datasource.password=password123
eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/

mq.exchange=ecommerce.exchange
mq.routing.stock=stock.rollback
mq.queue.stock=product.stock.compensation.queue
mq.routing.order-created=order.created