spring.application.name=api-gateway
server.port=8080

# Conexion a tu Eureka local
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# RUTA 1: Productos y Categorias
spring.cloud.gateway.server.webmvc.routes[0].id=product-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://ECOMMERCE-PRODUCT
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/product/**, /categoria/**, /subcategoria/**

# RUTA 2: Ordenes
spring.cloud.gateway.server.webmvc.routes[1].id=order-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://ECOMMERCE-ORDERS
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/order/**